/*
if 
if _else
else_if
switch case 
ternarary operator 
*/
//Boolean true/false 1-true 0-false 
//switch A-65 10101010
//if-else ladder 
// let num =3;
// if(num==7){
//   console.log("ravi");
// }
// else if (num==5){
//   console.log("yes its 5")
// }
// else{
//   console.log(false);
// }
////

//------------------ SwitchCase

//Operator operand 
//Operator + - * / % 
//incre ++ -- 
//Comparative oprators < > == === <= >=
//7 + 6 (operands are 5,6)

// function Calculator(opr,num1,num2){

//   switch(opr){
//     case '+' : console.log(num1+num2);break;
//     case '-' : console.log(num1-num2);break;
//     case '*' : console.log(num1*num2);break;
//     case '/' : console.log(num1/num2);break;
//     default : console.log("invalid input");
//   }
  
// }


// Calculator('+',5,6);

//ternarary Operator 
//Syntax - (condtion)?(true):(false);
let num2=8;
//(num2==8)?console.log("its 8"):console.log("its not 8");
// ! not operator 
//!true =false
//!false =true 
//(!false)?console.log("its 8"):console.log("its not 8");

